#!/usr/bin/env python3
"""Build the versioned nonlinear import identity table.

The historical verifier output binds each logical leaf label to its full
theorem-history digest.  A current HOL session separately emits an MD5 digest
of the serialized, hypothesis-free leaf proposition.  This tool joins those
two identities only after checking the two original verifier artifacts and
the checked-in historical digest table for exact label/digest agreement.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path


EXPECTED_RECORDS = 23_242
MD5_RE = r"[0-9a-f]{32}"
HASH_LINE_RE = re.compile(rf"^(\(.*,[0-9]+\):) ({MD5_RE})$")
ARCHIVE_LINE_RE = re.compile(r"^[0-9]+: [0-9]+,(\(.*,[0-9]+\):) ")
PAIR_LINE_RE = re.compile(
    rf'^\("(\(.*,[0-9]+\):)", "({MD5_RE})"\);$'
)
TRIPLE_LINE_RE = re.compile(
    rf'^\("(\(.*,[0-9]+\):)", "({MD5_RE})", "({MD5_RE})"\);$'
)
SURFACE_LINE_RE = re.compile(rf"^(\(.*,[0-9]+\):)\t({MD5_RE})$")


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def read_unique_records(path: Path, pattern: re.Pattern[str]) -> list[tuple[str, ...]]:
    records: list[tuple[str, ...]] = []
    seen: set[str] = set()
    for line_number, raw_line in enumerate(path.read_text().splitlines(), 1):
        match = pattern.match(raw_line)
        if match is None:
            continue
        record = match.groups()
        label = record[0]
        if label in seen:
            raise SystemExit(f"{path}:{line_number}: duplicate label {label}")
        seen.add(label)
        records.append(record)
    if len(records) != EXPECTED_RECORDS:
        raise SystemExit(
            f"{path}: expected {EXPECTED_RECORDS} records, found {len(records)}"
        )
    return records


def read_archive_labels(path: Path) -> list[str]:
    labels: list[str] = []
    seen: set[str] = set()
    for line_number, raw_line in enumerate(path.read_text().splitlines(), 1):
        match = ARCHIVE_LINE_RE.match(raw_line)
        if match is None:
            raise SystemExit(f"{path}:{line_number}: malformed archive record")
        label = match.group(1)
        if label in seen:
            raise SystemExit(f"{path}:{line_number}: duplicate label {label}")
        seen.add(label)
        labels.append(label)
    if len(labels) != EXPECTED_RECORDS:
        raise SystemExit(
            f"{path}: expected {EXPECTED_RECORDS} records, found {len(labels)}"
        )
    return labels


def read_historical_table(path: Path) -> list[tuple[str, str]]:
    records: list[tuple[str, str]] = []
    seen: set[str] = set()
    for line_number, raw_line in enumerate(path.read_text().splitlines(), 1):
        pair = PAIR_LINE_RE.match(raw_line)
        triple = TRIPLE_LINE_RE.match(raw_line)
        if pair is None and triple is None:
            continue
        label, digest = (pair or triple).groups()[:2]
        if label in seen:
            raise SystemExit(f"{path}:{line_number}: duplicate label {label}")
        seen.add(label)
        records.append((label, digest))
    if len(records) != EXPECTED_RECORDS:
        raise SystemExit(
            f"{path}: expected {EXPECTED_RECORDS} records, found {len(records)}"
        )
    return records


def as_mapping(name: str, records: list[tuple[str, str]]) -> dict[str, str]:
    mapping = dict(records)
    if len(mapping) != EXPECTED_RECORDS:
        raise SystemExit(f"{name}: label cardinality changed")
    return mapping


def render(
    historical_by_label: dict[str, str],
    surface_by_label: dict[str, str],
    input_hashes: dict[str, str],
) -> str:
    lines = [
        "(*",
        "   Versioned nonlinear theorem-import identities.",
        "",
        "   The historical full-history digests come from the original",
        "   nonlinear verifier.  The surface digests bind each logical leaf",
        "   to the exact serialized hypothesis-free proposition accepted by",
        "   the current compatibility importer.  Generated by",
        "   azure/scripts/build_nonlinear_import_manifest.py.",
        "",
    ]
    for name, digest in input_hashes.items():
        lines.append(f"   {name} sha256: {digest}")
    lines.extend(
        [
            "*)",
            "",
            "module Theorem_nonlinear_digest = struct",
            "",
            " let nonlinear_import_manifest_version = 1;;",
            f" let nonlinear_import_record_count = {EXPECTED_RECORDS};;",
            "",
            " let digest_records = [",
            "",
        ]
    )
    for label in sorted(historical_by_label):
        historical_digest = historical_by_label[label]
        surface_digest = surface_by_label[label]
        lines.append(
            f"({json.dumps(label)}, {json.dumps(historical_digest)}, "
            f"{json.dumps(surface_digest)});"
        )
    lines.extend(
        [
            "",
            "];;",
            "",
            " let digest_assoc_extern =",
            "   map (fun (label,history_digest,_) -> (label,history_digest))",
            "     digest_records;;",
            "",
            " let surface_digest_assoc_extern =",
            "   map (fun (label,_,surface_digest) -> (label,surface_digest))",
            "     digest_records;;",
            "",
            " let digest_list_extern = map snd digest_assoc_extern;;",
            "",
            "end ;;",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--archive", type=Path, required=True)
    parser.add_argument("--hashes", type=Path, required=True)
    parser.add_argument("--historical-table", type=Path, required=True)
    parser.add_argument("--surface-digests", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    archive_labels = read_archive_labels(args.archive)
    hashes = read_unique_records(args.hashes, HASH_LINE_RE)
    historical = read_historical_table(args.historical_table)
    surface = read_unique_records(args.surface_digests, SURFACE_LINE_RE)

    hashes_by_label = as_mapping("historical verifier hashes", hashes)
    historical_by_label = as_mapping("checked-in historical table", historical)
    surface_by_label = as_mapping("current surface digests", surface)
    archive_label_set = set(archive_labels)

    expected_labels = set(historical_by_label)
    if set(hashes_by_label) != expected_labels:
        raise SystemExit("historical verifier/table label sets differ")
    if archive_label_set != expected_labels:
        raise SystemExit("archive/table label sets differ")
    if set(surface_by_label) != expected_labels:
        raise SystemExit("surface/table label sets differ")
    if hashes_by_label != historical_by_label:
        raise SystemExit("historical verifier/table digest mappings differ")

    embedded_input_hashes = {
        "archive": sha256(args.archive),
        "historical hashes": sha256(args.hashes),
        "surface digest evidence": sha256(args.surface_digests),
        "generator": sha256(Path(__file__)),
    }
    audit_input_hashes = {
        **embedded_input_hashes,
        "historical table input": sha256(args.historical_table),
    }
    output = render(historical_by_label, surface_by_label, embedded_input_hashes)
    args.output.write_text(output, encoding="utf-8")
    print(
        json.dumps(
            {
                "records": EXPECTED_RECORDS,
                "output": str(args.output),
                "output_sha256": sha256(args.output),
                "inputs": audit_input_hashes,
            },
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
